# Generated by Django 3.1.8 on 2021-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suspension_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
