# Generated by Django 3.1.8 on 2021-05-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210506_1922'),
        ('customers', '0002_auto_20210506_1318'),
    ]

    operations = [
    ]
