# Generated by Django 3.1.8 on 2021-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_suspension_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
