# Generated by Django 3.1.8 on 2021-05-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_merge_20210506_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='suspension',
            field=models.BooleanField(blank=True, null=True, verbose_name=False),
        ),
    ]
