# Generated by Django 3.1.8 on 2021-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210506_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='suspension',
            field=models.BooleanField(default=False),
        ),
    ]
