# Generated by Django 3.1.8 on 2021-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
