# Generated by Django 3.1.8 on 2021-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
